export const NOOB_SPRITES = {
  player_idle_E:  { url: '../texture/player/player_idle_e.webp',  type: 'spritesheet', frames: 16, anchorX: 0.56, anchorY: 0.87, frameWidth: 48.5, frameHeight: 100, cols: 4, speed: 38},
  player_idle_SE:  { url: '../texture/player/player_idle_se.webp',  type: 'spritesheet', frames: 16, anchorX: 0.56, anchorY: 0.87, frameWidth: 54, frameHeight: 100, cols: 4, speed: 35},
  player_idle_NE:  { url: '../texture/player/player_idle_ne.webp',  type: 'spritesheet', frames: 16, anchorX: 0.56, anchorY: 0.87, frameWidth: 47.5, frameHeight: 100, cols: 4, speed: 34},
  player_run_E:  { url: '../texture/player/player_run_e.webp',  type: 'spritesheet', frames: 24, anchorX: 0.56, anchorY: 0.87, frameWidth: 61.166666, frameHeight: 100, cols: 6, speed: 32},
  player_run_NE:  { url: '../texture/player/player_run_ne.webp',  type: 'spritesheet', frames: 25, anchorX: 0.56, anchorY: 0.87, frameWidth: 53.6, frameHeight: 100, cols: 5, speed: 35},
  player_run_SE:  { url: '../texture/player/player_run_se.webp',  type: 'spritesheet', frames: 36, anchorX: 0.56, anchorY: 0.87, frameWidth: 49.1, frameHeight: 100, cols: 6, speed: 32},
  player_idle_laser_E:  { url: '../texture/player/player_idle_laser_e.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_idle_laser_SE:  { url: '../texture/player/player_idle_laser_se.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_idle_laser_NE:  { url: '../texture/player/player_idle_laser_ne.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_crawl_E:  { url: '../texture/player/player_crawl_e.png',  type: 'static', anchorX: 0.56, anchorY: 0.87},
  player_crawl_SE:  { url: '../texture/player/player_crawl_se.png',  type: 'static', anchorX: 0.5, anchorY: 0.8},
  player_crawl_NE:  { url: '../texture/player/player_crawl_ne.png',  type: 'static', anchorX: 0.5, anchorY: 0.8},
  player_cover_E:  { url: '../texture/player/player_cover_e.png',  type: 'static', anchorX: 0.5, anchorY: 0.87},
  player_cover_SE:  { url: '../texture/player/player_cover_se.png',  type: 'static', anchorX: 0.45, anchorY: 0.87},
  player_cover_NE:  { url: '../texture/player/player_cover_ne.png',  type: 'static', anchorX: 0.45, anchorY: 0.87},
  player_crawl_laser_E:  { url: '../texture/player/player_crawl_laser_e.png',  type: 'static', anchorX: 0.35, anchorY: 0.87},
  player_crawl_laser_SE:  { url: '../texture/player/player_crawl_laser_se.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_crawl_laser_NE:  { url: '../texture/player/player_crawl_laser_ne.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_idle_pistol_E:  { url: '../texture/player/player_idle_pistol_e.png',  type: 'static', anchorX: 0.35, anchorY: 0.9},
  player_idle_pistol_SE:  { url: '../texture/player/player_idle_pistol_se.png',  type: 'static', anchorX: 0.40, anchorY: 0.9},
  player_idle_pistol_NE:  { url: '../texture/player/player_idle_pistol_ne.png',  type: 'static', anchorX: 0.40, anchorY: 0.9},
  
  player_idle_E_shadow: { url: '../texture/player/player_idle_e_shadow.webp',  type: 'spritesheet', frames: 16, anchorX: 0.56, anchorY: 0.87, frameWidth: 48.5, frameHeight: 100, cols: 4, speed: 38},
  player_idle_SE_shadow:  { url: '../texture/player/player_idle_se_shadow.webp',  type: 'spritesheet', frames: 16, anchorX: 0.56, anchorY: 0.87, frameWidth: 54, frameHeight: 100, cols: 4, speed: 35},
  player_idle_NE_shadow:  { url: '../texture/player/player_idle_ne_shadow.webp',  type: 'spritesheet', frames: 16, anchorX: 0.56, anchorY: 0.87, frameWidth: 47.5, frameHeight: 100, cols: 4, speed: 34},
  player_run_E_shadow:  { url: '../texture/player/player_run_e_shadow.webp',  type: 'spritesheet', frames: 24, anchorX: 0.56, anchorY: 0.87, frameWidth: 61.166666, frameHeight: 100, cols: 6, speed: 32},
  player_run_NE_shadow:  { url: '../texture/player/player_run_ne_shadow.webp',  type: 'spritesheet', frames: 25, anchorX: 0.56, anchorY: 0.87, frameWidth: 53.6, frameHeight: 100, cols: 5, speed: 35},
  player_run_SE_shadow:  { url: '../texture/player/player_run_se_shadow.webp',  type: 'spritesheet', frames: 36, anchorX: 0.56, anchorY: 0.87, frameWidth: 49.1, frameHeight: 100, cols: 6, speed: 32},
  player_crawl_E_shadow: { url: '../texture/player/player_crawl_e_shadow.png',  type: 'static', anchorX: 0.5, anchorY: 0.87},
  player_crawl_SE_shadow: { url: '../texture/player/player_crawl_se_shadow.png',  type: 'static', anchorX: 0.45, anchorY: 0.84},
  player_crawl_NE_shadow: { url: '../texture/player/player_crawl_ne_shadow.png',  type: 'static', anchorX: 0.45, anchorY: 0.84},
  player_cover_E_shadow: { url: '../texture/player/player_cover_e_shadow.png',  type: 'static', anchorX: 0.5, anchorY: 0.87},
  player_cover_SE_shadow: { url: '../texture/player/player_cover_se_shadow.png',  type: 'static', anchorX: 0.45, anchorY: 0.84},
  player_cover_NE_shadow: { url: '../texture/player/player_cover_ne_shadow.png',  type: 'static', anchorX: 0.45, anchorY: 0.84},
  player_idle_laser_E_shadow:  { url: '../texture/player/player_idle_laser_e_shadow.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_idle_laser_SE_shadow:  { url: '../texture/player/player_idle_laser_se_shadow.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_idle_laser_NE_shadow:  { url: '../texture/player/player_idle_laser_ne_shadow.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_crawl_laser_E_shadow:  { url: '../texture/player/player_crawl_laser_e_shadow.png',  type: 'static', anchorX: 0.35, anchorY: 0.87},
  player_crawl_laser_SE_shadow:  { url: '../texture/player/player_crawl_laser_se_shadow.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_crawl_laser_NE_shadow:  { url: '../texture/player/player_crawl_laser_ne_shadow.png',  type: 'static', anchorX: 0.40, anchorY: 0.87},
  player_idle_pistol_E_shadow:  { url: '../texture/player/player_idle_pistol_e_shadow.png',  type: 'static', anchorX: 0.42, anchorY: 0.9},
  player_idle_pistol_SE_shadow:  { url: '../texture/player/player_idle_pistol_se_shadow.png',  type: 'static', anchorX: 0.42, anchorY: 0.85},
  player_idle_pistol_NE_shadow:  { url: '../texture/player/player_idle_pistol_ne_shadow.png',  type: 'static', anchorX: 0.42, anchorY: 0.85},
};